### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by FengqingWang0712** [jenniferlu717/Bracken#106]
Dear all,
I am new to use kraken and bracken. I used the kraken got the report.txt and tried to use bracken to estimate the abundance on Genus level. How ever, there is error said: >> Checking for Valid Options...
 >> Running Bracken 
/bin/bracken: line 98: [: /kraken_output_from_reads/bracken_output/319_10_genus_abundance_report.txt: unary operator expected
      >> python src/est_abundance.py -i /kraken_output_from_reads/319_10_2_archaea.report.txt -o /kraken_output_from_reads/bracken_output/319_10_genus_abundance.txt -k /kraken2/kraken2_db_archaea/database100mers.kmer_distrib -l G -t 32
PROGRAM START TIME: 07-24-2020 09:42:51
Traceback (most recent call last):
  File "/bin/src/est_abundance.py", line 488, in <module>
    main()
  File "/bin/src/est_abundance.py", line 222, in main
    report_vals = process_kraken_report(line)
  File "/bin/src/est_abundance.py", line 140, in process_kraken_report
    level_reads = int(split_str[2])
IndexError: list index out of range
here is the what I did in kraken2: 
kraken2 --db kraken2_db_archaea/ --paired --classified-out /kraken_output_from_reads/319_10_archaea_2#.fa /clean_data/20180319.clean.R1.fastq.gz /clean_data/20180319.clean.R2.fastq.gz --gzip-compressed --threads 16 --unclassified-out /kraken_output_from_reads/319_10_archaea.unclassify_2#.fa --use-names --report /kraken_output_from_reads/319_10_2_archaea.report.txt --use-mpa-style
and here is what I did in bracken:
bracken -d /kraken2/kraken2_db_archaea/ -i /kraken_output_from_reads/319_10_2_archaea.report.txt -o /kraken_output_from_reads/bracken_output/319_10_genus_abundance.txt -w /kraken_output_from_reads/bracken_output/319_10_genus_abundance_report.txt -r 100 -l G -t 32
[319_10_2_archaea.report.txt](https://github.com/jenniferlu717/Bracken/files/4971306/319_10_2_archaea.report.txt)

I also uploaded my report.txt. Full of appreciation for any suggestions.

**Comment by FengqingWang0712** [comment]
I found the reason. Thanks

**Comment by WPP7** [comment]
could you tell me how to solve it? I met the same issue currently.

**Comment by WPP7** [comment]
I think that's because of the params ` --use-mpa-style` .

**Comment by sunhaifeng123** [comment]
Hi,
I met the same question as you. I'm really puzzled by this problem for several days.

I used the code:

kraken2 --threads 60 --db ./k2_standard_16gb/ --gzip-compressed --memory-mapping --paired C2Input.rmrRNA.fq.1.gz C2Input.rmrRNA.fq.2.gz --report SAMPLE.Kraken.report --output SAMPLE.Kraken.result

bracken -d ./k2_standard_16gb -i SAMPLE.Kraken.report -o SAMPLE.bracken.report

and it report error:

> >> Checking report file: SAMPLE.Kraken.report
Traceback (most recent call last):
  File "/home/hs2244/app/Bracken2/src/est_abundance.py", line 554, in <module>
    main()
  File "/home/hs2244/app/Bracken2/src/est_abundance.py", line 323, in main
    elif main_lvls.index(level_id[0]) >= branch_lvl:
                         ~~~~~~~~^^^
IndexError: string index out of range

 Any reply will be appreciate!

Best,
Haifeng Sun
01/07/2024

**Comment by bajicv** [comment]
> Hi, I met the same question as you. I'm really puzzled by this problem for several days.
> 
> I used the code:
> 
> kraken2 --threads 60 --db ./k2_standard_16gb/ --gzip-compressed --memory-mapping --paired C2Input.rmrRNA.fq.1.gz C2Input.rmrRNA.fq.2.gz --report SAMPLE.Kraken.report --output SAMPLE.Kraken.result
> 
> bracken -d ./k2_standard_16gb -i SAMPLE.Kraken.report -o SAMPLE.bracken.report
> 
> and it report error:
> 
> > > > Checking report file: SAMPLE.Kraken.report
> > > > Traceback (most recent call last):
> > > > File "/home/hs2244/app/Bracken2/src/est_abundance.py", line 554, in 
> > > > main()
> > > > File "/home/hs2244/app/Bracken2/src/est_abundance.py", line 323, in main
> > > > elif main_lvls.index(level_id[0]) >= branch_lvl:
> > > > ~~~~~~~~^^^
> > > > IndexError: string index out of range
> 
> Any reply will be appreciate!
> 
> Best, Haifeng Sun 01/07/2024

Hi Haifeng Sun! 

I also encountered the same error, and it turned out that I used a kraken2 version that was not completely compatible with bracken. 

Initially I created reports using `kraken version 2.1.2` and tried to run `Bracken v2.9` but it resulted in the above-mentioned error. 

I checked the report files and realized that some of the rank codes were missing (4th column in kraken2 report). This caused `est_abundance.py` to break. If you are lazy, you can manually add "-" where rank codes are missing and bracken should run successfully. A better option would be to run kraken2 version supported by bracken (e.g. the one that comes with conda installation, in my case that was `kraken version 2.1.3` and `bracken v2.9`).

Example of report differences between kraken version 2.1.2 (not suitable for bracken v2.9) and 2.1.3 (suitable for bracken v2.9):

Kraken version 2.1.2 report:
```
 99.31	50442912	0		1	root
 96.06	48792700	165		2	    Bacteria
  3.25	1650204	0		2759	    Eukaryota
```

Kraken version 2.1.3 report:
```
 99.31	50442912	0	R	1	root
 96.06	48792700	165	D	2	    Bacteria
  3.25	1650204	0	D	2759	    Eukaryota
```
Note that "R", "D", and "D" are missing in the 4th column of the kraken version 2.1.2 report.

I hope choosing the correct kraken2 version would resolve your problem too!
