### ISSUE TITLE
error running final script

### ISSUE THREAD

**Issue by skerker** [jenniferlu717/Bracken#11]
I was able to generate all the necessary files (I used PE data to make the .kraken file and my own custom database) - but now the final script throws an error.   

Not sure what information you might need from me to help troubleshoot - but here is the error message.

Thanks again,
Jeff

[1]+  Running                 est_abundance.py -i ./APAJMS001_R1.kraken -k ./KMER_DISTR.TXT -o ./APAJMS001_R1.kraken.bracken &

bash-4.1$ Traceback (most recent call last):
  File "/usr2/people/skerker/mySoftware/Bracken-1.0.0/est_abundance.py", line 456, in <module>
    main()
  File "/usr2/people/skerker/mySoftware/Bracken-1.0.0/est_abundance.py", line 284, in main
    for child_node in curr_node.children:
AttributeError: 'int' object has no attribute 'children'

**Comment by jenniferlu717** [comment]
That error message is common actually, mostly because I wasn't clear enough when specifying what file to use.

for the est_abundance program, you want to use the kraken REPORT file, not the kraken direct output. 

To generate the kraken report file, use:

> kraken-report --db $DBNAME kraken.output > kraken.report

and then use the kraken.report file as the input to the est_abundance.py program

**Comment by skerker** [comment]
It works now.  Thank you!
