### ISSUE TITLE
The question about -r parameter

### ISSUE THREAD

**Issue by z1242099843** [jenniferlu717/Bracken#196]
In the help manual the -r parameter is described as  Read length, but I wonder if this read is raw reads or clean read after processing? If the raw read length of my data is 150, would it be better if I set the -r parameter to feed 100?

**Comment by zztin** [comment]
Hi, 
I have the same question. We are sequencing cell-free DNA reads, therefore the read length after adapter trimming is shroter than the sequencing read length, and it is not always the same length. Do you have a good suggestion on how to set the -r parameter? For example, based on the average read length after trimming?

**Comment by jenniferlu717** [comment]
Read length should be the approximately the shortest read length you have after processing. When testing, we used 75bp for 75bp paired reads (150 bp reads)

**Comment by schorlton** [comment]
Given that adapter/quality trimming can produce a long tail of reads with short read lengths, would you suggest I only allow a minimum length of 50bp and then use `-r 50`? Even if the vast majority of my reads may be ~150bp PE (manually stitched together as `{R1_seq}x{R2_seq}`)? What is the shortest read Kraken2 could theoretically classify? It feels weird to throw out reads with short length if they're otherwise valid, and/or to preprocess specifically for kraken2 if my other downstream tools could make use of reads <50bp.
