### ISSUE TITLE
Running bracken on mini kraken db

### ISSUE THREAD

**Issue by Bonder-MJ** [jenniferlu717/Bracken#2]
Hi, 
First of thanks for the tool! 
We are trying to run bracken on a mini kraken database. However, since not all K-mers are in the DB after shrinking we get unclassified K-mers during the first step in bracken. What is the best way to proceed? We can use the full db to get the required files by bracken and use this on the samples which are classified using the mini kraken DB, or take out the non-classified K-mers and continue the bracken steps? Thanks for the help.

Regards,
Marc Jan

PS. There is a typo in the readme.md it says: BKRACKEN instead of BRACKEN

**Comment by jenniferlu717** [comment]
Thanks for noticing the typo, I'll fix that as soon as I get to my computer.

Regarding unclassified reads, it's more accurate if the original kraken database does not include them. If the reads are unclassified by kraken because your kraken database does not contain the genomes  (and you don't care about detecting them) then bracken will leave the reads as unclassified. (Regardless of whether they are in the bracken input files. You can include them or you can ignore them. It won't change the calculation). We ignore genomes not found uniquely by kraken to avoid false positives. 


If you include the genomes in the kraken database but do not use them in making the bracken input files, then the reads will not be distributed to those genomes and the estimation will be off.

Hope that helps

**Comment by Bonder-MJ** [comment]
Thanks for this really quick reply.

Sorry if I was unclear but I wasnt talking about genomes but k-mers derived
from the genomes. We use the same genomes to build the mini kraken DB as to
classify during the first bracken step. However since in the process of
making the database smaller (creating a mini kraken DB, from a full one)
some k-mers are removed. Because of this, not all possible k-mers from the
genomes are classified in the first bracken step.

So my question should we run bracken on the full DB, before making the
mini, and use the information from these initial bracken steps to
re-estimate samples classified with the mini kraken DB. Or should we run
bracken directly on the mini DB, remove the non classified k-mers found in
the first step and continue and use this information for the eventual
kraken classified sampels

Thanks again!
Marc Jan

Op do 2 jun. 2016 16:53 schreef jenniferlu717 <notifications@github.com>:

**Comment by jenniferlu717** [comment]
I would suggest running bracken directly on the mini DB. You won't need to remove the non-classified k-mers because bracken will just ignore those. The current version of bracken makes two files, one kraken-style report which will list the unclassified kmers as the first line and a second file that will list the species abundances based on the classified kmers.

**Comment by Bonder-MJ** [comment]
Thanks!

Op do 2 jun. 2016 17:24 schreef jenniferlu717 <notifications@github.com>:

**Comment by Bonder-MJ** [comment]
Dear Jennifer,

The current code doesn't work with the unclasified kmers as encounterd in
the mini-kraken DB. We uncommented the lines:
https://github.com/jenniferlu717/Bracken/blob/master/count-kmer-abundances.pl#L111-L119

And then changed the 'A' to 0, if the zero's are not escaped the code
doesn't work.

Cheers,
Marc Jan

**Comment by fbreitwieser** [comment]
Dear Marc Jan,
Can you try again with the newest version? It should work now.
