### ISSUE TITLE
Any plan to support kraken2?

### ISSUE THREAD

**Issue by ghbore** [jenniferlu717/Bracken#43]
Dear developer, is there any plan to support kraken2 (https://github.com/DerrickWood/kraken2)?

**Comment by jenniferlu717** [comment]
Kraken2 works with Bracken the same exact way that Kraken 1 does, just use the new kraken2-build command instead of kraken-build (same with kraken2 instead of kraken). 

The results are nearly identical if the kraken1/kraken2 databases are built with the exact same sequences but obviously kraken2 requires less memory and time.
